name: news
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  dio: ^5.3.3
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  html: ^0.15.4
  easy_refresh: ^3.3.2+1
  dotted_line: ^3.2.2
  flutter_html: ^3.0.0-beta.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.4
  path_provider: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
